default:
  image: debian:sid
  before_script:
    - apt-get update --yes
    - apt-get install --yes build-essential qt5-qmake qtbase5-dev qtmultimedia5-dev
      libqt5svg5-dev qtscript5-dev rsync libusb-1.0-0-dev python3-dev
      libqt5serialport5-dev libudev-dev libqt5svg5-dev qtwayland5
      qtbase5-private-dev qttools5-dev-tools ccache
    - uname -a
    - rsync --version
    - qmake --version && qmake -query
    - ccache --version

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - qmake CONFIG+=release CONFIG+=tests CONFIG+=noPch CONFIG+=ccache
      CONFIG+=trik_not_brick CONFIG+=trik_nopython
      ..
    - make -j $(nproc) qmake_all
    - make -j $(nproc) all
    - make -k check TESTARGS="-platform offscreen"
