name: "No Python on Debian Sid on RISC-V"
on:
  push:
    branches:
  pull_request:
    branches:
  workflow_dispatch:

jobs:
  debian:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} # to force import of ~/.bash_profile
    strategy:
      matrix:
        # nopython: ["nopython"]
        # qjsengine: [""] # add 'qjsengine' for CONFIG+=trik_use_qjsengine
        # qt-version: ['5.12']
        # gcc-version: ['11']
        arch: ["riscv64"]
        distro: ["debian:sid"]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      # - name: Cancel Previous Workflow Runs
      #   uses: n1hility/cancel-previous-runs@v2.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.arch }}

      - name: Configure git
        run: |
          git --version
          git config --global core.symlinks true
          git config --global core.autocrlf false

          #prepare for actions/checkout, otherwise it fails
          echo "LC_ALL=en_US.utf8" >> $GITHUB_ENV
          echo "$(dirname $(realpath $(which git)))" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PERL5LIB=$PERL5LIB" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Run in Docker
        run: |
          docker run \
            --rm \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            --platform linux/${{ matrix.arch }} \
            ${{ matrix.distro }} \
            scripts/run_in_qemu.sh
